# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: checkout
    displayName: PullRepo
    steps:
      - script: |
         docker pull nginx:latest
         docker tag nginx:latest reddynaresh76/testrepo:$(Build.BuildNumber)
         docker push reddynaresh76/testrepo:$(Build.BuildNumber)

  - job: variables_handler
    displayName: Create artifact from variables
    steps:
      - script: |
         echo { '"test21"' : '"$(Build.BuildNumber)"' , '"test12"' : '"$(Build.DefinitionName)"' } >  $(Build.ArtifactStagingDirectory)/pipeline.json
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'